version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: tracker-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  tracker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracker-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Variabel database
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # Variabel display untuk X11
      DISPLAY: ${DISPLAY}
    ports:
      - "3000:3000"
    # Akses perangkat input (X11, keyboard, mouse)
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    # Akses devices
    devices:
      - /dev/input:/dev/input
    privileged: true

volumes:
  postgres_data:
